# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
#permalink:        pretty

# Setup
title:            Splitting Atoms
tagline:          'a guide to hacking on Atom'
description:      'a community-built, community-driven guide to hacking on the <a href="https://atom.io">Atom</a> editor'
url:              https://jbranchaud.github.io/splitting-atoms

author:
  name:           'Josh Branchaud'
  url:            https://twitter.com/jbrancha

paginate:         5
paginate_path:    "blog/page:num"

# Custom vars
version:          0.0.0

twitter:          https://twitter.com/Splitting_Atoms
github:
  repo:           https://github.com/jbranchaud/splitting-atoms
